openapi: 3.0.1
info:
  title: BibliotecaAPILivro
  description: API Definition of LivroCreateAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/livro
paths:
  /livro/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
